import { Transaction } from "@/types/types";

export const transactions: Transaction[] = [
    {
      orderId: '12345',
      billingName: 'John Doe',
      date: '2024-06-10',
      total: 100.00,
      paymentStatus: 'Paid',
      paymentMethod: 'Credit Card',
    },
    {
      orderId: '54321',
      billingName: 'Jane Smith',
      date: '2024-06-09',
      total: 75.50,
      paymentStatus: 'Pending',
      paymentMethod: 'PayPal',
    },
    {
      orderId: '98765',
      billingName: 'Alice Johnson',
      date: '2024-06-08',
      total: 200.00,
      paymentStatus: 'Paid',
      paymentMethod: 'Debit Card',
    },
    {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },
      {
        orderId: '98765',
        billingName: 'Alice Johnson',
        date: '2024-06-08',
        total: 200.00,
        paymentStatus: 'Paid',
        paymentMethod: 'Debit Card',
      },

  ];